import { NextRequest, NextResponse } from "next/server";
import { writeFileSync, copyFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import type { SavedProject, SavedImage } from "@/lib/reports";

// Save the currently-active project as the /demo snapshot.
//
// What this does:
// 1. Copies every referenced cache image into `public/demo-images/` so it can
//    be served statically on Vercel (the runtime `.cache/` folder won't exist
//    in production).
// 2. Rewrites every image URL in the project from `/api/serve-image/x.jpg` to
//    `/demo-images/x.jpg`.
// 3. Writes the rewritten project to `lib/demo-project.ts` as a typed export.
//
// After hitting save, commit the generated file + the new image assets to git
// so the demo survives deploys. Dev-only — production has no write access.

const CACHE_DIR = join(process.cwd(), ".cache", "images");
const PUBLIC_DEMO_DIR = join(process.cwd(), "public", "demo-images");
const DEMO_FILE = join(process.cwd(), "lib", "demo-project.ts");

function rewriteImageUrl(url: string | undefined): string | undefined {
  if (!url) return url;
  const match = url.match(/^\/api\/serve-image\/(.+)$/);
  if (!match) return url;
  const filename = match[1];
  const source = join(CACHE_DIR, filename);
  if (!existsSync(source)) return url;
  mkdirSync(PUBLIC_DEMO_DIR, { recursive: true });
  const dest = join(PUBLIC_DEMO_DIR, filename);
  copyFileSync(source, dest);
  return `/demo-images/${filename}`;
}

function rewriteStringMap(
  map: Record<string, SavedImage> | undefined,
): Record<string, SavedImage> {
  if (!map) return {};
  const out: Record<string, SavedImage> = {};
  for (const [k, v] of Object.entries(map)) {
    out[k] = { ...v, url: rewriteImageUrl(v.url) || v.url };
  }
  return out;
}

function rewriteNumberMap(
  map: Record<number, SavedImage> | undefined,
): Record<number, SavedImage> {
  if (!map) return {};
  const out: Record<number, SavedImage> = {};
  for (const [k, v] of Object.entries(map)) {
    out[Number(k)] = { ...v, url: rewriteImageUrl(v.url) || v.url };
  }
  return out;
}

export async function POST(request: NextRequest) {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json(
      { error: "save-demo is dev-only. Commit lib/demo-project.ts to persist the snapshot." },
      { status: 403 },
    );
  }

  try {
    const project = (await request.json()) as SavedProject;
    if (!project || !project.jsonData) {
      return NextResponse.json({ error: "Missing project data" }, { status: 400 });
    }

    const rewritten: SavedProject = {
      ...project,
      images: rewriteNumberMap(project.images),
      posterImages: rewriteNumberMap(project.posterImages),
      portraits: rewriteStringMap(project.portraits),
      propImages: rewriteStringMap(project.propImages),
    };

    const fileContent = `// Auto-generated by POST /api/save-demo.
// Commit this file (and public/demo-images/) to git to preserve the demo.

import type { SavedProject } from "./reports";

export const DEMO_PROJECT: SavedProject | null = ${JSON.stringify(
      rewritten,
      null,
      2,
    )};
`;
    writeFileSync(DEMO_FILE, fileContent);

    return NextResponse.json({
      ok: true,
      title: rewritten.title,
      imageCount:
        Object.keys(rewritten.images || {}).length +
        Object.keys(rewritten.posterImages || {}).length +
        Object.keys(rewritten.portraits || {}).length +
        Object.keys(rewritten.propImages || {}).length,
    });
  } catch (error) {
    console.error("Save demo error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Save failed" },
      { status: 500 },
    );
  }
}
